Weights:
  # DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3NESTED-GIANT-LARGE-1.1'
  # DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3-BASE'
  DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3-LARGE-1.1'
Model:
  keyframe_interval: 1 # extract 1 frame in every n frames
  chunk_size: 15 # frame size for a chunk >2
  overlap_size: 1 # 
  sleep_between_chunk: 10
  port: 8080

  Align:

  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  ICP:


Loop:
  SIM3_Optimizer:
    max_iterations: 30
    lambda_init: 1e-6
