Weights:
  # DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3NESTED-GIANT-LARGE-1.1'
  # DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3-BASE'
  DA3: '/home/zhouyi/repo/Depth-Anything-3/checkpoints/DA3-LARGE-1.1'
Model:
  keyframe_interval: 30 # 每n帧抽取1帧关键帧用于重构
  chunk_size: 10 # 处理块大小
  overlap_size: 1 # 
  sleep_demo: 1000
  port: 8080

  Align:

  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

Loop:
  SIM3_Optimizer:
    max_iterations: 30
    lambda_init: 1e-6
